compile::stdout 0

compile::stderr 10
tests2/inputs/break_invalid_location.own:4:5:[1;31merror[0;39m:break statement outside of a for loop
     3 | fn main() i32 {
     4 |     break
       |     ^
     5 |     let num i32 = 9
tests2/inputs/break_invalid_location.own:6:5:[1;31merror[0;39m:continue statement outside of a for loop
     5 |     let num i32 = 9
     6 |     continue
       |     ^
     7 |     return 0

compile::return_code 1

